### PR TITLE
Fix pass through of keep-alive agent. Fixes #61

### LINKED ISSUE #61: 1.x does not allow to pass Agent to request options
I noticed that the 1.x branch includes a bug that makes it impossible to pass custom http.Agent to http.request thus making keep-alive impossible.

Please check this line:
https://github.com/najaxjs/najax/blob/master/lib/najax.js#L97

### PR DESCRIPTION
**Pull request by WooDzu**
Fixes https://github.com/najaxjs/najax/issues/61

Currently there is no way to pass through the 'agent' property from 'options' to xhr request making keep-alive impossible. It was passible in pre 1.x released. Likely an an oversight. 

**Expected:**

If the 'agent'  is specified in provided 'options' it should be passed through to xhr.

Please approve.

### CODE REVIEW

File: lib/najax.js [hunk 1]
```diff
@@ -92,9 +92,9 @@ function najax (uri, options, callback) {
   } else if (o.auth) {
     options.auth = o.auth
   }
+  /* pass keep-alive agent if provided */
+  if (o.agent) options.agent = o.agent
 
-  if (options.auth) o.auth = options.auth
-  if (options.agent) o.agent = options.agent
```
Comment (WooDzu) [inline lib/najax.js]: These two lines have no effect. 

> if (options.auth) o.auth = options.auth
Not needed as handed already in the AUTHENTICATION block above

> if (options.agent) o.agent = options.agent
This should be the other way around.
